image:
  file: .gitpod.Dockerfile

tasks:
  - name: Install dependencies
    init: |
      poetry env use python
      poetry install

vscode:
  extensions:
    - ms-python.python
    - ms-toolsai.jupyter

github:
  prebuilds:
    master: true
    pullRequests: true
